insert into dyr(id,latinsk_navn,navn) values (1,'Aphis spp.','Bladlus');
insert into dyr(id,latinsk_navn,navn) values (2,'Tetranychus urticae','Spinnmidd');
insert into dyr(id,latinsk_navn,navn) values (3,'Arion vulgaris','Brunskogsnegl');
insert into dyr(id,latinsk_navn,navn) values (4,'Limax maximus','Pantersnegl');
insert into dyr(id,latinsk_navn,navn) values (5,'Otiorhynchus sulcatus','Vinsnutebille');
insert into dyr(id,latinsk_navn,navn) values (6,'Thrips tabaci','Trips');
insert into dyr(id,latinsk_navn,navn) values (7,'Trialeurodes vaporariorum','Hvitfly');
insert into dyr(id,latinsk_navn,navn) values (8,'Agriotes spp.','Smellerlarver');
insert into dyr(id,latinsk_navn,navn) values (9,'Delia radicum','Kålflue');
insert into dyr(id,latinsk_navn,navn) values (10,'Pieris brassicae','Kålsommerfugl');
insert into dyr(id,latinsk_navn,navn) values (11,'Coccinella septempunctata','Marihøne');
insert into dyr(id,latinsk_navn,navn) values (12,'Chrysoperla carnea','Gulløye');
insert into dyr(id,latinsk_navn,navn) values (13,'Bombus terrestris','Humle');
insert into dyr(id,latinsk_navn,navn) values (14,'Apis mellifera','Honningbie');
insert into dyr(id,latinsk_navn,navn) values (15,'Syrphidae','Blomsterflue');
insert into dyr(id,latinsk_navn,navn) values (16,'Lumbricus terrestris','Meitemark');
insert into dyr(id,latinsk_navn,navn) values (17,'Formica rufa','Rød skogsmaur');
insert into dyr(id,latinsk_navn,navn) values (18,'Forficula auricularia','Ørentvist');
insert into dyr(id,latinsk_navn,navn) values (19,'Carabus nemoralis','Løpebille');
insert into dyr(id,latinsk_navn,navn) values (20,'Staphylinidae','Kortvinger');
insert into dyr(id,latinsk_navn,navn) values (21,'Talpa europaea','Muldvarp');
insert into dyr(id,latinsk_navn,navn) values (22,'Microtus agrestis','Markmus');
insert into dyr(id,latinsk_navn,navn) values (23,'Arvicola amphibius','Vannrotte');
insert into dyr(id,latinsk_navn,navn) values (24,'Cervus elaphus','Hjort');
insert into dyr(id,latinsk_navn,navn) values (25,'Capreolus capreolus','Rådyr');
insert into dyr(id,latinsk_navn,navn) values (26,'Lepus timidus','Hare');
insert into dyr(id,latinsk_navn,navn) values (27,'Sciurus vulgaris','Ekorn');
insert into dyr(id,latinsk_navn,navn) values (28,'Erinaceus europaeus','Pinnsvin');
insert into dyr(id,latinsk_navn,navn) values (29,'Parus major','Kjøttmeis');
insert into dyr(id,latinsk_navn,navn) values (30,'Turdus merula','Svarttrost');
insert into dyr(id,latinsk_navn,navn) values (31,'Helix aspersa','Hagesnegl');
insert into dyr(id,latinsk_navn,navn) values (32,'Deroceras reticulatum','Åkersnegl');
insert into dyr(id,latinsk_navn,navn) values (33,'Aleyrodidae','Skjoldlus');
insert into dyr(id,latinsk_navn,navn) values (34,'Psylla spp.','Sugere');
insert into dyr(id,latinsk_navn,navn) values (35,'Noctuidae','Nattfly-larver');
insert into dyr(id,latinsk_navn,navn) values (36,'Vespula vulgaris','Vanlig veps');
insert into dyr(id,latinsk_navn,navn) values (37,'Ichneumonidae','Snylteveps');
insert into dyr(id,latinsk_navn,navn) values (38,'Phyllobius oblongus','Snutebille');
insert into dyr(id,latinsk_navn,navn) values (39,'Bibio marci','Russeflue');
insert into dyr(id,latinsk_navn,navn) values (40,'Tipula paludosa','Stankelbeinlarve');
insert into dyr(id,latinsk_navn,navn) values (41,'Canis lupus familiaris','Hund');
insert into dyr(id,latinsk_navn,navn) values (42,'Felis catus','Katt');
insert into dyr(id,latinsk_navn,navn) values (43,'Gallus gallus domesticus','Høne');
insert into dyr(id,latinsk_navn,navn) values (44,'Anas platyrhynchos','Stokkand');
insert into dyr(id,latinsk_navn,navn) values (45,'Corvus cornix','Kråke');
insert into dyr(id,latinsk_navn,navn) values (46,'Mus musculus','Husmus');
insert into dyr(id,latinsk_navn,navn) values (47,'Rattus norvegicus','Brunrotte');
insert into dyr(id,latinsk_navn,navn) values (48,'Sturnus vulgaris','Stær');
insert into dyr(id,latinsk_navn,navn) values (49,'Vanessa atalanta','Admiralsommerfugl');
insert into dyr(id,latinsk_navn,navn) values (50,'Aglais urticae','Neslesommerfugl');